version: 2.1

commands:
  install-dependencies:
    description: |
      Install dependencies
    steps:
      - run: npm install

  dev-build-commands:
    description: |
      Create a staging build
    steps:
      - run: |
          # echo $GCS_SERVICE_ACCOUNT_PATH > .env
          NODE_ENV=production CI=false 
          npm run build
      - run: mkdir -p build && cp -r dist/* build && cp -r node_modules package.json public build/

  dev-deploy-commands:
    description: |
      Deploying to the staging AWS
    steps:
      - add_ssh_keys:
          fingerprints:
            - $FINGERPRINT
      - run: |
          echo "Deploying"
          cd build && tar -cvzf 'wizard-cms.tar' *
          mkdir -p ~/.ssh
          touch ~/.ssh/config
          echo -e "Host *\n\tStrictHostKeyChecking no\n\n" >> ~/.ssh/config
          scp -i fingerprints 'wizard-cms.tar' ubuntu@54.91.102.33:/home/ubuntu/
          echo "copied wizard-cms.tar"
          ssh -i fingerprints ubuntu@54.91.102.33 'ls && mkdir -p data/services/wizard-cms && cd data/services/wizard-cms && rm -rf public  src config  database  node_modules build'
          ssh -i fingerprints ubuntu@54.91.102.33 'ls && mkdir -p data/services/wizard-cms && tar -xvzf wizard-cms.tar -C data/services/wizard-cms/ && rm wizard-cms.tar'
          echo "create wizard-cms dir and untar"
          ssh -i fingerprints ubuntu@54.91.102.33 'pm2 list | (grep wizard-cms && pm2 restart wizard-cms) || (cd data/services/wizard-cms && pm2 start --name wizard-cms npm -- run start)'
          echo "Deployment Success"

executors:
  default:
    description: |
      Node Runtime Environment
    docker:
      - image: cimg/node:<<parameters.node>>
    parameters:
      node:
        default: "20.13.1"
        type: string

jobs:
  build-dev:
    description: |
      Build the production application, and stores the assets in artifacts
    executor: default
    steps:
      - attach_workspace:
          at: ~/
      - dev-build-commands
      - store_artifacts:
          path: ./artifacts
      - persist_to_workspace:
          paths:
            - project
          root: ~/

  deploy-dev:
    description: |
      Build the production application, and stores the assets in artifacts
    executor: default
    steps:
      - attach_workspace:
          at: ~/
      - dev-deploy-commands

  install:
    description: |
      Install dependencies
    executor: default
    parameters:
      before_install:
        default:
          - checkout
        description: |
          Steps to be executed before restoring cache and running install. Default is to run 'checkout' command.
        type: steps

    steps:
      - steps: <<parameters.before_install>>
      - restore_cache:
          key: v1-node-modules-{{ checksum "package-lock.json" }}
      - install-dependencies
      - persist_to_workspace:
          paths:
            - project
          root: ~/
      - save_cache:
          key: v1-node-modules-{{ checksum "package-lock.json" }}
          paths:
            - ~/project/node_modules

workflows:
  app-build:
    jobs:
      - install:
          filters:
            branches:
              only:
                - main
      - build-dev:
          requires:
            - install
          filters:
            branches:
              only:
                - main
